name: Deploy to Render

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Accept: application/json" \
            -d '{}' \
            https://api.render.com/v1/services/YOUR_SERVICE_ID/deploys

      - name: Notify on Deployment Success
        run: |
          echo "Deployment successful!"
          # Add any notification command here, for example:
          # curl -X POST -H "Content-Type: application/json" -d '{"text":"Deployment Successful!"}' YOUR_SLACK_WEBHOOK_URL

